-- +goose Up
-- +goose StatementBegin
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'schema_owner') THEN
    EXECUTE 'CREATE ROLE schema_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'migration_role') THEN
    EXECUTE 'CREATE ROLE migration_role NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'api_runtime_role') THEN
    EXECUTE 'CREATE ROLE api_runtime_role NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'worker_runtime_role') THEN
    EXECUTE 'CREATE ROLE worker_runtime_role NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'audit_append_owner') THEN
    EXECUTE 'CREATE ROLE audit_append_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ops_readonly_role') THEN
    EXECUTE 'CREATE ROLE ops_readonly_role NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS';
  END IF;
END
$$;
-- +goose StatementEnd

ALTER ROLE schema_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE migration_role NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE api_runtime_role NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE worker_runtime_role NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE audit_append_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE ops_readonly_role NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

GRANT schema_owner TO migration_role;
GRANT audit_append_owner TO schema_owner WITH ADMIN OPTION;
GRANT SELECT, INSERT, UPDATE ON public.goose_db_version TO migration_role;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS platform AUTHORIZATION schema_owner;
CREATE SCHEMA IF NOT EXISTS finding AUTHORIZATION schema_owner;
CREATE SCHEMA IF NOT EXISTS incident AUTHORIZATION schema_owner;
CREATE SCHEMA IF NOT EXISTS investigation AUTHORIZATION schema_owner;
CREATE SCHEMA IF NOT EXISTS action AUTHORIZATION schema_owner;
CREATE SCHEMA IF NOT EXISTS audit AUTHORIZATION schema_owner;
ALTER SCHEMA platform OWNER TO schema_owner;
ALTER SCHEMA finding OWNER TO schema_owner;
ALTER SCHEMA incident OWNER TO schema_owner;
ALTER SCHEMA investigation OWNER TO schema_owner;
ALTER SCHEMA action OWNER TO schema_owner;
ALTER SCHEMA audit OWNER TO schema_owner;

SET ROLE schema_owner;
CREATE TABLE platform.tenants (
  tenant_id uuid PRIMARY KEY,
  slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  display_name text NOT NULL CHECK (length(display_name) BETWEEN 1 AND 200),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
RESET ROLE;

GRANT USAGE ON SCHEMA platform TO api_runtime_role, worker_runtime_role, ops_readonly_role;
GRANT SELECT, INSERT, UPDATE ON platform.tenants TO api_runtime_role;
GRANT SELECT ON platform.tenants TO worker_runtime_role, ops_readonly_role;
