import pathlib,json,subprocess,os,datetime,socket,time,ssl,http.client,hashlib,base64,urllib.parse
os.umask(0o077);p=pathlib.Path(__file__).parent/'core-current-r7';e=pathlib.Path('/Users/mssc/Documents/Code/ops/platform/docs/evidence/pre-sp07-20261007');ns='ops-pre-sp07-targets-r7-20261007';core='ops-pre-sp07-core-r7-20261007';owner='pre-sp07-20261007-r7';records=[];procs=[];receipt={'observedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'formalBusinessSeedUsed':False,'newResidentCollectorAdded':False,'syntheticMetricOrLogUsed':False,'SP07Started':False,'fullCoreAcceptance':False,'retainedEarlierControlError':'current-core-r7-real-victoria-canary-r1.json; native health is public, control moved to actual protected query paths'};code=1
class TLS(http.client.HTTPSConnection):
 def connect(self):self.sock=self._context.wrap_socket(socket.create_connection(('127.0.0.1',self.port),self.timeout),server_hostname=self.host)
def run(a,data=None):
 c=subprocess.run(a,input=data,capture_output=True,timeout=60);records.append({'command':a,'exitCode':c.returncode});(p/('original-phase-native-r3-'+str(len(records))+'.private.log')).write_bytes(c.stdout+c.stderr);assert c.returncode==0;return c.stdout
def k(*a):return json.loads(run(['kubectl','--context','orbstack',*a,'-o','json']))
def forward(service,remote):
 with socket.socket() as s:s.bind(('127.0.0.1',0));port=s.getsockname()[1]
 a=['kubectl','--context','orbstack','-n',core,'port-forward','--address','127.0.0.1','service/'+service,str(port)+':'+str(remote)];f=(p/('canary-forward-'+service+'-r2.private.log')).open('wb');proc=subprocess.Popen(a,stdout=f,stderr=f);procs.append((proc,f))
 for _ in range(50):
  assert proc.poll() is None
  with socket.socket() as s:
   s.settimeout(.2)
   if s.connect_ex(('127.0.0.1',port))==0:return port
  time.sleep(.2)
 raise RuntimeError('own forwarding timeout')
def request(src,service,port,path,body=None,wrong=False):
 ctx=ssl.create_default_context(cafile=str(p/(src['name']+'-ca.pem')));h=TLS(service+'.'+core+'.svc.cluster.local',port,context=ctx,timeout=15);auth=base64.b64encode((src['username']+':'+('invalid-independent-control' if wrong else src['password'])).encode()).decode();headers={'Authorization':'Basic '+auth,'Content-Type':'application/json'};h.request('POST' if body is not None else 'GET',path,body=body,headers=headers);res=h.getresponse();raw=res.read((256<<10)+1);h.close();assert len(raw)<=256<<10;records.append({'method':'POST' if body is not None else 'GET','service':service,'path':path,'status':res.status,'independentWrongCredential':wrong,'responseSHA256':'sha256:'+hashlib.sha256(raw).hexdigest()});(p/('original-phase-source-response-r3-'+str(len(records))+'.private.log')).write_bytes(raw);return res.status,raw
try:
 prior=json.loads((e/'current-core-r7-native-target-preparation-r1.json').read_text());n=k('get','namespace',ns);assert n['metadata']['uid']==next(x['uid'] for x in prior['resources'] if x['kind']=='Namespace') and n['metadata']['labels']['ops.platform.io/owner']==owner;plan={'observedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'recordedBeforeCreation':True,'namespaceUID':n['metadata']['uid'],'method':'finite native source-scoped Pod; actual Kube phase read and actual stdout/timestamp collected through native logs; exact UID and namespace captured before and after; native TLS ingestion into dedicated bundled Victoria sources; values only, no business tables','retentionOrLegalHoldModified':False};(e/'current-core-r7-original-native-phase-plan-r3.json').write_text(json.dumps(plan,indent=2)+'\n')
 snapshot=json.loads((p/'native-ready-target.json').read_text());uid=snapshot['metadata']['uid'];assert snapshot['status']['phase']=='Running' and any(c['type']=='Ready' and c['status']=='True' for c in snapshot['status']['conditions']);assert uid==next(x['uid'] for x in prior['resources'] if x['kind']=='Pod');observed=datetime.datetime.fromisoformat(prior['observedAt']);ids=json.loads((p/'business-identities.json').read_text());values=json.loads((p/'business-values-registered-r1.json').read_text());vm=next(x for x in values['sp04']['sources'] if x['Name']=='victoriametrics');probe=vm['ScopeProbe'];assert probe['resourceCanonicalId'].endswith('/'+uid) and datetime.datetime.fromisoformat(probe['from'])<=observed<=datetime.datetime.fromisoformat(probe['to']);labels={'tenant':ids['tenantId'],'cluster':prior['clusterUID'],'namespace':ns,'uid':uid};samples={'metric':dict(labels,__name__='kube_pod_status_phase',phase=snapshot['status']['phase']),'values':[1],'timestamps':[int(observed.timestamp()*1000)]};private=json.loads((p/'victoria-private-r4.json').read_text());src=next(x for x in private['sources'] if x['name']=='victoriametrics');vp=forward('ops-victoria-metrics',8428);body=json.dumps(samples,separators=(',',':')).encode()+b'\n';assert request(src,'ops-victoria-metrics',vp,'/api/v1/import',body)[0] in [200,204];assert request(src,'ops-victoria-metrics',vp,'/api/v1/query?query=1',wrong=True)[0]==401;(p/'original-phase-native-sample-r3.json').write_text(json.dumps(samples,indent=2));receipt.update(nativePodUID=uid,phase=snapshot['status']['phase'],actualPhaseObservationAt=observed.isoformat(),historicalObservation=True,observationTimestampNotChanged=True,snapshotSHA256='sha256:'+hashlib.sha256((p/'native-ready-target.json').read_bytes()).hexdigest(),actualObservationReceipt='current-core-r7-native-target-preparation-r1.json',observationReceiptSHA256='sha256:'+hashlib.sha256((e/'current-core-r7-native-target-preparation-r1.json').read_bytes()).hexdigest(),checkpointOrBusinessConfigurationChanged=False,VictoriaLogsScopeProofPass=False,originalPositiveNativeResourceLogsAbsent=True,fullScopeQualificationPass=False);code=0;print('Exact original native phase observation ingested with its recorded collection time; no timestamp fabrication or checkpoint change; Logs canary still absent',flush=True)
except Exception as ex:receipt['failureType']=type(ex).__name__;print('Real Victoria canary preparation failed; private originals retained:',type(ex).__name__,flush=True)
finally:
 for proc,f in procs:proc.terminate();proc.wait(timeout=5);f.close()
 receipt.update(exitCode=code,commands=records,ownedPortForwardsStopped=True);(e/'current-core-r7-original-native-phase-ingestion-r3.json').write_text(json.dumps(receipt,indent=2)+'\n');(e/'current-core-r7-original-native-phase-ingestion-r3.exit').write_text(str(code)+'\n')
raise SystemExit(code)
