import pathlib,json,subprocess,os,datetime,socket,time,ssl,http.client,hashlib,base64,urllib.parse
os.umask(0o077);p=pathlib.Path(__file__).parent/'core-current-r7';e=pathlib.Path('/Users/mssc/Documents/Code/ops/platform/docs/evidence/pre-sp07-20261007');ns='ops-pre-sp07-targets-r7-20261007';core='ops-pre-sp07-core-r7-20261007';owner='pre-sp07-20261007-r7';records=[];procs=[];receipt={'observedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'formalBusinessSeedUsed':False,'newResidentCollectorAdded':False,'syntheticMetricOrLogUsed':False,'SP07Started':False,'fullCoreAcceptance':False};code=1
class TLS(http.client.HTTPSConnection):
 def connect(self):self.sock=self._context.wrap_socket(socket.create_connection(('127.0.0.1',self.port),self.timeout),server_hostname=self.host)
def run(a,data=None):
 c=subprocess.run(a,input=data,capture_output=True,timeout=60);records.append({'command':a,'exitCode':c.returncode});(p/('real-victoria-canary-r1-'+str(len(records))+'.private.log')).write_bytes(c.stdout+c.stderr);assert c.returncode==0;return c.stdout
def k(*a):return json.loads(run(['kubectl','--context','orbstack',*a,'-o','json']))
def forward(service,remote):
 with socket.socket() as s:s.bind(('127.0.0.1',0));port=s.getsockname()[1]
 a=['kubectl','--context','orbstack','-n',core,'port-forward','--address','127.0.0.1','service/'+service,str(port)+':'+str(remote)];f=(p/('canary-forward-'+service+'-r1.private.log')).open('wb');proc=subprocess.Popen(a,stdout=f,stderr=f);procs.append((proc,f))
 for _ in range(50):
  assert proc.poll() is None
  with socket.socket() as s:
   s.settimeout(.2)
   if s.connect_ex(('127.0.0.1',port))==0:return port
  time.sleep(.2)
 raise RuntimeError('own forwarding timeout')
def request(src,service,port,path,body=None,wrong=False):
 ctx=ssl.create_default_context(cafile=str(p/(src['name']+'-ca.pem')));h=TLS(service+'.'+core+'.svc.cluster.local',port,context=ctx,timeout=15);auth=base64.b64encode((src['username']+':'+('invalid-independent-control' if wrong else src['password'])).encode()).decode();headers={'Authorization':'Basic '+auth,'Content-Type':'application/json'};h.request('POST' if body is not None else 'GET',path,body=body,headers=headers);res=h.getresponse();raw=res.read((256<<10)+1);h.close();assert len(raw)<=256<<10;records.append({'method':'POST' if body is not None else 'GET','service':service,'path':path,'status':res.status,'independentWrongCredential':wrong,'responseSHA256':'sha256:'+hashlib.sha256(raw).hexdigest()});(p/('canary-source-response-r1-'+str(len(records))+'.private.log')).write_bytes(raw);return res.status,raw
try:
 prior=json.loads((e/'current-core-r7-native-target-preparation-r1.json').read_text());n=k('get','namespace',ns);assert n['metadata']['uid']==next(x['uid'] for x in prior['resources'] if x['kind']=='Namespace') and n['metadata']['labels']['ops.platform.io/owner']==owner;plan={'observedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'recordedBeforeCreation':True,'namespaceUID':n['metadata']['uid'],'method':'finite native source-scoped Pod; actual Kube phase read and actual stdout/timestamp collected through native logs; exact UID and namespace captured before and after; native TLS ingestion into dedicated bundled Victoria sources; values only, no business tables','retentionOrLegalHoldModified':False};(e/'current-core-r7-real-victoria-canary-plan-r1.json').write_text(json.dumps(plan,indent=2)+'\n')
 base=json.loads((p/'native-ready-target.json').read_text());spec=base['spec'];spec.pop('nodeName',None);spec.pop('tolerations',None);spec['activeDeadlineSeconds']=1800;cont=spec['containers'][0];cont['command']=['/bin/bash','-ec','echo "native-readiness-started uid=$TARGET_UID namespace=$TARGET_NAMESPACE"; sleep 1700'];cont['env']=[{'name':'TARGET_UID','valueFrom':{'fieldRef':{'fieldPath':'metadata.uid'}}},{'name':'TARGET_NAMESPACE','valueFrom':{'fieldRef':{'fieldPath':'metadata.namespace'}}}];obj={'apiVersion':'v1','kind':'Pod','metadata':{'name':'pre-sp07-current-r7-source-canary','namespace':ns,'labels':base['metadata']['labels']},'spec':spec};live=json.loads(run(['kubectl','--context','orbstack','create','-f','-','-o','json'],json.dumps(obj).encode()));uid=live['metadata']['uid'];run(['kubectl','--context','orbstack','wait','--for=condition=Ready','pod/'+live['metadata']['name'],'-n',ns,'--timeout=60s']);live=k('get','pod',live['metadata']['name'],'-n',ns);assert live['metadata']['uid']==uid and live['status']['phase']=='Running';observed=datetime.datetime.now(datetime.timezone.utc);rawlog=run(['kubectl','--context','orbstack','logs',live['metadata']['name'],'-n',ns,'--timestamps=true','--limit-bytes=4096']);lines=rawlog.decode().strip().splitlines();assert len(lines)==1;stamp,msg=lines[0].split(' ',1);assert msg=='native-readiness-started uid='+uid+' namespace='+ns;start=datetime.datetime.fromisoformat(stamp.replace('Z','+00:00'));assert start>=datetime.datetime.fromisoformat(live['metadata']['creationTimestamp'].replace('Z','+00:00'));again=k('get','pod',live['metadata']['name'],'-n',ns);assert again['metadata']['uid']==uid and again['status']['phase']==live['status']['phase'];ids=json.loads((p/'business-identities.json').read_text());labels={'tenant':ids['tenantId'],'cluster':prior['clusterUID'],'namespace':ns,'uid':uid};samples={'metric':dict(labels,__name__='kube_pod_status_phase',phase=live['status']['phase']),'values':[1],'timestamps':[int(observed.timestamp()*1000)]};log=dict(labels,_time=stamp,_msg=msg);private=json.loads((p/'victoria-private-r4.json').read_text());sources={x['name']:x for x in private['sources']};vp=forward('ops-victoria-metrics',8428);lp=forward('ops-victoria-logs',9428);body=json.dumps(samples,separators=(',',':')).encode()+b'\n';assert request(sources['victoriametrics'],'ops-victoria-metrics',vp,'/api/v1/import',body)[0] in [200,204];body=json.dumps(log,separators=(',',':')).encode()+b'\n';assert request(sources['victorialogs'],'ops-victoria-logs',lp,'/insert/jsonline',body)[0] in [200,204];assert request(sources['victoriametrics'],'ops-victoria-metrics',vp,'/health',wrong=True)[0]==401;assert request(sources['victorialogs'],'ops-victoria-logs',lp,'/health',wrong=True)[0]==401
 values=json.loads((p/'business-values-registered-r1.json').read_text());fromtime=min(start,observed)-datetime.timedelta(seconds=60);totime=max(start,observed)+datetime.timedelta(seconds=45);cid='k8s+v1://'+ids['tenantId']+'/'+prior['clusterUID']+'/core/Pod/'+uid
 for s in values['sp04']['sources']:s['ScopeProbe'].update(resourceCanonicalId=cid,**{'from':fromtime.isoformat(),'to':totime.isoformat()})
 (p/'business-values-real-canary-r1.json').write_text(json.dumps(values,indent=2)+'\n');(p/'native-victoria-canary-r1.json').write_text(json.dumps(again,indent=2));(p/'real-victoria-native-samples-r1.json').write_text(json.dumps({'metric':samples,'log':log,'observedAt':observed.isoformat()},indent=2));receipt.update(nativePodUID=uid,namespaceUID=n['metadata']['uid'],canonicalId=cid,node=live['spec']['nodeName'],nativePhase=live['status']['phase'],phaseCollectedAt=observed.isoformat(),nativeStartupLogTimestamp=stamp,nativeStartupLogSHA256='sha256:'+hashlib.sha256(rawlog).hexdigest(),boundedProbeFrom=fromtime.isoformat(),boundedProbeTo=totime.isoformat(),finiteActiveDeadlineSeconds=1800,sourceTLSVerifiedWithExactServiceSAN=True,independentInvalidCredential401=True,installerValuesSHA256='sha256:'+hashlib.sha256((p/'business-values-real-canary-r1.json').read_bytes()).hexdigest(),adapterScopeProofPass=False);code=0;print('Real native phase and actual startup log captured with stable UID, ingested over strict source TLS; no synthetic business data or source proof bypass',flush=True)
except Exception as ex:receipt['failureType']=type(ex).__name__;print('Real Victoria canary preparation failed; private originals retained:',type(ex).__name__,flush=True)
finally:
 for proc,f in procs:proc.terminate();proc.wait(timeout=5);f.close()
 receipt.update(exitCode=code,commands=records,ownedPortForwardsStopped=True);(e/'current-core-r7-real-victoria-canary-r1.json').write_text(json.dumps(receipt,indent=2)+'\n');(e/'current-core-r7-real-victoria-canary-r1.exit').write_text(str(code)+'\n')
raise SystemExit(code)
