import pathlib,subprocess,socket,time,http.client,json,hashlib,datetime,os,urllib.parse,uuid
os.umask(0o077);p=pathlib.Path(__file__).parent/'core-current-r7';e=pathlib.Path('/Users/mssc/Documents/Code/ops/platform/docs/evidence/pre-sp07-20261007');records=[];proc=None;f=None;code=1;receipt={'observedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'historicalCanaryObservationOnly':True,'currentModelMCPChainPass':False,'completeCoreAcceptance':False,'VictoriaLogsScopeProofPass':False,'SP07Started':False,'checkpointConfigurationOrProtectedDataChanged':False}
def request(path,body=None,identity=None,tenant=None):
 h=http.client.HTTPConnection('127.0.0.1',port,timeout=15);headers={'Authorization':'Bearer '+(p/'fresh-loa2.token').read_text().strip()}
 if identity:headers['Idempotency-Key']=identity
 if body is not None:headers['Content-Type']='application/json'
 if tenant:headers['X-Tenant-ID']=tenant
 h.request('POST' if body is not None else 'GET',path,body=json.dumps(body,separators=(',',':')).encode() if body is not None else None,headers=headers);r=h.getresponse();raw=r.read((1<<20)+1);h.close();assert len(raw)<=1<<20;(p/('formal-victoria-phase-api-r1-'+str(len(records))+'.private.log')).write_bytes(raw);records.append({'method':'POST' if body is not None else 'GET','path':path,'status':r.status,'idempotencyKeySHA256':'sha256:'+hashlib.sha256(identity.encode()).hexdigest() if identity else None,'responseSHA256':'sha256:'+hashlib.sha256(raw).hexdigest()});return r.status,raw
try:
 values=json.loads((p/'business-values-registered-r1.json').read_text());source=next(x for x in values['sp04']['sources'] if x['Name']=='victoriametrics');logs=next(x for x in values['sp04']['sources'] if x['Name']=='victorialogs');probe=source['ScopeProbe'];recovered=json.loads((e/'current-core-r7-scheduling-state-observation-r2.json').read_text());cid=recovered['currentCanonicalId']
 with socket.socket() as s:s.bind(('127.0.0.1',0));port=s.getsockname()[1]
 a=['kubectl','--context','orbstack','-n','ops-pre-sp07-core-r7-20261007','port-forward','--address','127.0.0.1','service/ops-api',str(port)+':8080'];f=(p/'victoria-phase-api-forward-r1.private.log').open('wb');proc=subprocess.Popen(a,stdout=f,stderr=f)
 for _ in range(50):
  assert proc.poll() is None
  with socket.socket() as s:
   s.settimeout(.2)
   if s.connect_ex(('127.0.0.1',port))==0:break
  time.sleep(.2)
 else:raise RuntimeError('own forward unavailable')
 for _ in range(30):
  status,raw=request('/api/v1/resources/by-canonical-id?'+urllib.parse.urlencode({'canonicalId':cid}));assert status==200;graph=json.loads(raw)['data']
  if graph['degradedSources']==[logs['Binding']['SourceID']+'/proof']:break
  time.sleep(2)
 else:raise RuntimeError('actual positive Metrics scope proof absent')
 assert graph['partial'] and graph['freshness']=='fresh' and graph['warnings']==['source_scope_unverified'];body={'resourceCanonicalId':probe['resourceCanonicalId'],'type':'metrics','queryTemplate':probe['queryTemplate'],'timeRange':{'from':probe['from'],'to':probe['to']},'budget':{'timeoutMs':3000,'maxBytes':65536},'sourceRegistrationId':source['Binding']['SourceID'],'namespace':probe['namespace'],'limit':1};key=str(uuid.uuid4());status,raw=request('/api/v1/evidence:query',body,key);assert status==200;result=json.loads(raw)['data'];assert result['freshness']=='fresh' and not result['partial'] and len(result['evidence'])==1;item=result['evidence'][0];assert item['resourceCanonicalId']==probe['resourceCanonicalId'] and item['sourceRegistrationId']==source['Binding']['SourceID'] and item['archiveRef']['object']['versionId'] and item['replayState']=='archived_verified';status,raw=request('/api/v1/evidence/'+item['evidenceId']);assert status==200;read=json.loads(raw)['data'];digest='sha256:'+hashlib.sha256(json.dumps(read['factSlice'],separators=(',',':'),ensure_ascii=False).encode()).hexdigest();assert digest==read['contentDigest']==item['contentDigest'];assert read['factSlice']['rows']
 status,raw=request('/api/v1/evidence:query',body,key);assert status==200;again=json.loads(raw)['data']['evidence'][0];assert again['evidenceId']==item['evidenceId'] and again['contentDigest']==digest and again['archiveRef']['object']['versionId']==item['archiveRef']['object']['versionId'];bad=dict(body);bad['resourceCanonicalId']=body['resourceCanonicalId'].replace('676d5ba5-0f08-433b-be13-8012ea7e3591','ddca03c9-eba6-456d-b1e2-d28bb8c79525',1);status,_=request('/api/v1/evidence:query',bad,str(uuid.uuid4()));assert status==403;cross=status;bad=dict(body);bad.update(type='logs',queryTemplate=logs['ScopeProbe']['queryTemplate'],sourceRegistrationId=logs['Binding']['SourceID']);status,raw=request('/api/v1/evidence:query',bad,str(uuid.uuid4()));assert status==503 and json.loads(raw)['code']=='SOURCE_SCOPE_UNVERIFIED';receipt.update(actualPositiveVictoriaScopeProof=True,actualAuthenticatedAPIAdapterArchiveReadback=True,evidenceId=item['evidenceId'],contentDigest=digest,archiveVersionId=item['archiveRef']['object']['versionId'],retainUntil=item['archiveRef']['object']['retainUntil'],sourceRegistrationId=source['Binding']['SourceID'],resourceCanonicalId=item['resourceCanonicalId'],sourceQueryWindow=body['timeRange'],historicalFactsPresentedAsCurrent=False,actualIdempotentReplaySameEvidenceAndArchiveVersion=True,crossTenantEvidenceStatus=cross,unverifiedLogsSourceStatus=status,unverifiedLogsSourceErrorCode='SOURCE_SCOPE_UNVERIFIED',currentSchedulingGraphFreshness=graph['freshness'],currentGraphPartial=True,currentDegradedSources=graph['degradedSources'],currentWarnings=graph['warnings'],noSourceUnavailabilityReportedAsRecovery=True);code=0;print('Actual original VictoriaMetrics canary -> scope proof -> authenticated API -> Transit/versioned retained Archive -> identical idempotent readback; foreign tenant403 and unverified Logs503; Graph honestly partial',flush=True)
except Exception as ex:receipt['failureType']=type(ex).__name__;print('Formal Victoria phase/API gate failed; private evidence retained:',type(ex).__name__,flush=True)
finally:
 if proc:proc.terminate();proc.wait(timeout=5)
 if f:f.close()
 receipt.update(exitCode=code,requests=records,ownedPortForwardStopped=True);(e/'current-core-r7-victoria-phase-formal-api-r1.json').write_text(json.dumps(receipt,indent=2)+'\n');(e/'current-core-r7-victoria-phase-formal-api-r1.exit').write_text(str(code)+'\n')
raise SystemExit(code)
