{{- if not .Values.networkPolicyOnly }}
{{- range $name, $component := .Values.components }}
{{- if or $component.enabled (and $.Values.sp06.enabled (eq $name "investigator")) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-{{ $name }}
  labels:
    ops.platform.io/release: {{ $.Release.Name | quote }}
    ops.platform.io/component: {{ $name }}
automountServiceAccountToken: false
---
{{- end }}
{{- end }}
{{- end }}
