{{- if not .Values.networkPolicyOnly }}
{{- range $name, $component := .Values.components }}
{{- if $component.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-{{ $name }}
  labels:
    ops.platform.io/release: {{ $.Release.Name | quote }}
    ops.platform.io/component: {{ $name }}
automountServiceAccountToken: false
---
{{- end }}
{{- end }}
{{- end }}
