{{- if not .Values.networkPolicyOnly }}
{{- range $name, $component := .Values.components }}
{{- if $component.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ops-{{ $name }}
  labels:
    ops.platform.io/release: {{ $.Release.Name | quote }}
    ops.platform.io/component: {{ $name }}
spec:
  type: ClusterIP
  selector:
    ops.platform.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $component.port }}
      targetPort: http
---
{{- end }}
{{- end }}
{{- end }}
