// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActionExecution struct {
	TenantID                  pgtype.UUID        `json:"tenant_id"`
	ExecutionID               pgtype.UUID        `json:"execution_id"`
	Subject                   string             `json:"subject"`
	TargetCanonicalID         string             `json:"target_canonical_id"`
	Shell                     string             `json:"shell"`
	CommandDigest             string             `json:"command_digest"`
	RiskAcknowledgementID     pgtype.UUID        `json:"risk_acknowledgement_id"`
	ExecutionProfileVersionID pgtype.UUID        `json:"execution_profile_version_id"`
	IdempotencyKeyDigest      string             `json:"idempotency_key_digest"`
	State                     string             `json:"state"`
	CommandArchiveRef         pgtype.Text        `json:"command_archive_ref"`
	OutputArchiveRef          pgtype.Text        `json:"output_archive_ref"`
	ExitCode                  pgtype.Int4        `json:"exit_code"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type ActionRiskAcknowledgement struct {
	TenantID          pgtype.UUID        `json:"tenant_id"`
	AcknowledgementID pgtype.UUID        `json:"acknowledgement_id"`
	Subject           string             `json:"subject"`
	TargetCanonicalID string             `json:"target_canonical_id"`
	Shell             string             `json:"shell"`
	CommandDigest     string             `json:"command_digest"`
	RiskLevel         string             `json:"risk_level"`
	PolicyVersionID   pgtype.UUID        `json:"policy_version_id"`
	StepUpSessionID   pgtype.UUID        `json:"step_up_session_id"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
}

type AuditRecord struct {
	AuditSeq        pgtype.Int8        `json:"audit_seq"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	TenantSeq       int64              `json:"tenant_seq"`
	RecordID        pgtype.UUID        `json:"record_id"`
	EventType       string             `json:"event_type"`
	EntityKind      string             `json:"entity_kind"`
	EntityID        pgtype.UUID        `json:"entity_id"`
	Subject         string             `json:"subject"`
	Record          []byte             `json:"record"`
	CanonicalDigest []byte             `json:"canonical_digest"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AuditSegment struct {
	TenantID          pgtype.UUID        `json:"tenant_id"`
	SegmentID         pgtype.UUID        `json:"segment_id"`
	FirstTenantSeq    int64              `json:"first_tenant_seq"`
	LastTenantSeq     int64              `json:"last_tenant_seq"`
	MerkleRoot        string             `json:"merkle_root"`
	Signature         []byte             `json:"signature"`
	SigningKeyVersion pgtype.Text        `json:"signing_key_version"`
	ObjectRef         pgtype.Text        `json:"object_ref"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SignedAt          pgtype.Timestamptz `json:"signed_at"`
}

type AuditTenantHead struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	LastTenantSeq int64       `json:"last_tenant_seq"`
}

type FindingInbox struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EventID       string             `json:"event_id"`
	SourceID      pgtype.UUID        `json:"source_id"`
	RequestDigest string             `json:"request_digest"`
	State         string             `json:"state"`
	FindingID     pgtype.UUID        `json:"finding_id"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
}

type FindingOutbox struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	OutboxID      pgtype.UUID        `json:"outbox_id"`
	FindingID     pgtype.UUID        `json:"finding_id"`
	EventType     string             `json:"event_type"`
	SchemaVersion string             `json:"schema_version"`
	Payload       []byte             `json:"payload"`
	State         string             `json:"state"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	ClaimToken    pgtype.UUID        `json:"claim_token"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type FindingRecord struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	FindingID     pgtype.UUID        `json:"finding_id"`
	SourceID      pgtype.UUID        `json:"source_id"`
	ClusterID     pgtype.UUID        `json:"cluster_id"`
	SchemaVersion string             `json:"schema_version"`
	EventID       string             `json:"event_id"`
	Payload       []byte             `json:"payload"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type IncidentFindingLink struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	IncidentID pgtype.UUID        `json:"incident_id"`
	FindingID  pgtype.UUID        `json:"finding_id"`
	LinkedAt   pgtype.Timestamptz `json:"linked_at"`
}

type IncidentRecord struct {
	TenantID   pgtype.UUID        `json:"tenant_id"`
	IncidentID pgtype.UUID        `json:"incident_id"`
	State      string             `json:"state"`
	Revision   int64              `json:"revision"`
	Summary    string             `json:"summary"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type InvestigationJob struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	JobID           pgtype.UUID        `json:"job_id"`
	IncidentID      pgtype.UUID        `json:"incident_id"`
	TriggerRevision int64              `json:"trigger_revision"`
	PolicyVersionID pgtype.UUID        `json:"policy_version_id"`
	State           string             `json:"state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type InvestigationWorkerQueue struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	JobID          pgtype.UUID        `json:"job_id"`
	LeaseOwner     pgtype.Text        `json:"lease_owner"`
	LeaseToken     pgtype.UUID        `json:"lease_token"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	HeartbeatAt    pgtype.Timestamptz `json:"heartbeat_at"`
	FencingEpoch   int64              `json:"fencing_epoch"`
	Attempts       int32              `json:"attempts"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
}

type PlatformClusterRegistration struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ClusterID   pgtype.UUID        `json:"cluster_id"`
	ClusterUid  string             `json:"cluster_uid"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	Revision    int64              `json:"revision"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PlatformClusterRegistrationRevision struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ClusterID    pgtype.UUID        `json:"cluster_id"`
	Revision     int64              `json:"revision"`
	ClusterUid   string             `json:"cluster_uid"`
	DisplayName  string             `json:"display_name"`
	Status       string             `json:"status"`
	ActorSubject string             `json:"actor_subject"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PlatformExecutionProfileVersion struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ProfileVersionID pgtype.UUID        `json:"profile_version_id"`
	LogicalName      string             `json:"logical_name"`
	VersionNumber    int32              `json:"version_number"`
	Content          []byte             `json:"content"`
	Digest           string             `json:"digest"`
	Signature        []byte             `json:"signature"`
	SignerKeyID      string             `json:"signer_key_id"`
	Status           string             `json:"status"`
	PublishedBy      string             `json:"published_by"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
}

type PlatformIdempotencyRequestLedger struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	LedgerID             pgtype.UUID        `json:"ledger_id"`
	Subject              string             `json:"subject"`
	Operation            string             `json:"operation"`
	IdempotencyKeyDigest string             `json:"idempotency_key_digest"`
	RequestDigest        string             `json:"request_digest"`
	ExecutionOnce        bool               `json:"execution_once"`
	State                string             `json:"state"`
	LeaseToken           pgtype.UUID        `json:"lease_token"`
	LeaseExpiresAt       pgtype.Timestamptz `json:"lease_expires_at"`
	Attempt              int32              `json:"attempt"`
	ResponseStatus       pgtype.Int4        `json:"response_status"`
	ResponseContentType  pgtype.Text        `json:"response_content_type"`
	ResponseHeaders      []byte             `json:"response_headers"`
	ResponseBody         []byte             `json:"response_body"`
	ResponseExpiresAt    pgtype.Timestamptz `json:"response_expires_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type PlatformRegistryActivation struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ActivationID pgtype.UUID        `json:"activation_id"`
	Kind         string             `json:"kind"`
	LogicalName  string             `json:"logical_name"`
	ScopeType    string             `json:"scope_type"`
	ClusterID    pgtype.UUID        `json:"cluster_id"`
	Namespace    pgtype.Text        `json:"namespace"`
	VersionID    pgtype.UUID        `json:"version_id"`
	Revision     int64              `json:"revision"`
	ActivatedBy  string             `json:"activated_by"`
	ActivatedAt  pgtype.Timestamptz `json:"activated_at"`
}

type PlatformRegistryActivationHistory struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ActivationID pgtype.UUID        `json:"activation_id"`
	Revision     int64              `json:"revision"`
	Kind         string             `json:"kind"`
	LogicalName  string             `json:"logical_name"`
	ScopeType    string             `json:"scope_type"`
	ClusterID    pgtype.UUID        `json:"cluster_id"`
	Namespace    pgtype.Text        `json:"namespace"`
	VersionID    pgtype.UUID        `json:"version_id"`
	ActivatedBy  string             `json:"activated_by"`
	ActivatedAt  pgtype.Timestamptz `json:"activated_at"`
}

type PlatformRegistryDraft struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	DraftID     pgtype.UUID        `json:"draft_id"`
	Kind        string             `json:"kind"`
	LogicalName string             `json:"logical_name"`
	Revision    int64              `json:"revision"`
	Content     []byte             `json:"content"`
	Status      string             `json:"status"`
	UpdatedBy   string             `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PlatformRegistryVersion struct {
	TenantID      pgtype.UUID        `json:"tenant_id"`
	VersionID     pgtype.UUID        `json:"version_id"`
	DraftID       pgtype.UUID        `json:"draft_id"`
	Kind          string             `json:"kind"`
	LogicalName   string             `json:"logical_name"`
	VersionNumber int32              `json:"version_number"`
	Content       []byte             `json:"content"`
	Digest        string             `json:"digest"`
	Signature     []byte             `json:"signature"`
	SignerKeyID   string             `json:"signer_key_id"`
	PublishedBy   string             `json:"published_by"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	RetiredAt     pgtype.Timestamptz `json:"retired_at"`
}

type PlatformRoleBinding struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	BindingID       pgtype.UUID        `json:"binding_id"`
	Subject         string             `json:"subject"`
	RoleName        string             `json:"role_name"`
	ClusterScopes   []byte             `json:"cluster_scopes"`
	NamespaceScopes []byte             `json:"namespace_scopes"`
	Status          string             `json:"status"`
	Revision        int64              `json:"revision"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PlatformSourceRegistration struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	SourceID           pgtype.UUID        `json:"source_id"`
	SourceType         string             `json:"source_type"`
	InstanceKey        string             `json:"instance_key"`
	ClusterID          pgtype.UUID        `json:"cluster_id"`
	AuthRef            string             `json:"auth_ref"`
	CredentialRevision int64              `json:"credential_revision"`
	Status             string             `json:"status"`
	Config             []byte             `json:"config"`
	Revision           int64              `json:"revision"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type PlatformSourceRegistrationRevision struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	SourceID           pgtype.UUID        `json:"source_id"`
	Revision           int64              `json:"revision"`
	AuthRef            string             `json:"auth_ref"`
	CredentialRevision int64              `json:"credential_revision"`
	Status             string             `json:"status"`
	Scope              []byte             `json:"scope"`
	ActorSubject       string             `json:"actor_subject"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type PlatformStepUpSession struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	Subject     string             `json:"subject"`
	KeycloakSid string             `json:"keycloak_sid"`
	Acr         string             `json:"acr"`
	AuthTime    pgtype.Timestamptz `json:"auth_time"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type PlatformTenant struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Status      string             `json:"status"`
	Revision    int64              `json:"revision"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
