// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ListPublishedRegistryVersions(ctx context.Context, tenantID pgtype.UUID) ([]ListPublishedRegistryVersionsRow, error)
	ListRoleBindings(ctx context.Context, tenantID pgtype.UUID) ([]ListRoleBindingsRow, error)
	ListSourceRegistrations(ctx context.Context, tenantID pgtype.UUID) ([]ListSourceRegistrationsRow, error)
}

var _ Querier = (*Queries)(nil)
