// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPublishedRegistryVersions = `-- name: ListPublishedRegistryVersions :many
SELECT version_id, kind, logical_name, version_number, digest, signer_key_id, published_at
FROM platform.registry_versions
WHERE tenant_id = $1
ORDER BY kind, logical_name, version_number DESC
`

type ListPublishedRegistryVersionsRow struct {
	VersionID     pgtype.UUID        `json:"version_id"`
	Kind          string             `json:"kind"`
	LogicalName   string             `json:"logical_name"`
	VersionNumber int32              `json:"version_number"`
	Digest        string             `json:"digest"`
	SignerKeyID   string             `json:"signer_key_id"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListPublishedRegistryVersions(ctx context.Context, tenantID pgtype.UUID) ([]ListPublishedRegistryVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedRegistryVersions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedRegistryVersionsRow
	for rows.Next() {
		var i ListPublishedRegistryVersionsRow
		if err := rows.Scan(
			&i.VersionID,
			&i.Kind,
			&i.LogicalName,
			&i.VersionNumber,
			&i.Digest,
			&i.SignerKeyID,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindings = `-- name: ListRoleBindings :many
SELECT binding_id, subject, role_name, cluster_scopes, namespace_scopes, status, revision
FROM platform.role_bindings
WHERE tenant_id = $1
ORDER BY subject, binding_id
`

type ListRoleBindingsRow struct {
	BindingID       pgtype.UUID `json:"binding_id"`
	Subject         string      `json:"subject"`
	RoleName        string      `json:"role_name"`
	ClusterScopes   []byte      `json:"cluster_scopes"`
	NamespaceScopes []byte      `json:"namespace_scopes"`
	Status          string      `json:"status"`
	Revision        int64       `json:"revision"`
}

func (q *Queries) ListRoleBindings(ctx context.Context, tenantID pgtype.UUID) ([]ListRoleBindingsRow, error) {
	rows, err := q.db.Query(ctx, listRoleBindings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoleBindingsRow
	for rows.Next() {
		var i ListRoleBindingsRow
		if err := rows.Scan(
			&i.BindingID,
			&i.Subject,
			&i.RoleName,
			&i.ClusterScopes,
			&i.NamespaceScopes,
			&i.Status,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceRegistrations = `-- name: ListSourceRegistrations :many
SELECT source_id, source_type, instance_key, cluster_id, status, credential_revision, revision
FROM platform.source_registrations
WHERE tenant_id = $1
ORDER BY source_type, instance_key
`

type ListSourceRegistrationsRow struct {
	SourceID           pgtype.UUID `json:"source_id"`
	SourceType         string      `json:"source_type"`
	InstanceKey        string      `json:"instance_key"`
	ClusterID          pgtype.UUID `json:"cluster_id"`
	Status             string      `json:"status"`
	CredentialRevision int64       `json:"credential_revision"`
	Revision           int64       `json:"revision"`
}

func (q *Queries) ListSourceRegistrations(ctx context.Context, tenantID pgtype.UUID) ([]ListSourceRegistrationsRow, error) {
	rows, err := q.db.Query(ctx, listSourceRegistrations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSourceRegistrationsRow
	for rows.Next() {
		var i ListSourceRegistrationsRow
		if err := rows.Scan(
			&i.SourceID,
			&i.SourceType,
			&i.InstanceKey,
			&i.ClusterID,
			&i.Status,
			&i.CredentialRevision,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
